var js =  
`{
    "0": {
        "0": {
            "cnum": "121",
            "cname": "Intro Problem Solving W/Comp",
            "credits": 4,
            "pid": 4,
            "lid": 100,
            "honors": false,
            "location": "TBD",
            "gened": "R2",
            "major": "COMPSCI",
            "prereqs": "TBD",
            "time_of_day": "TU TH 5:30PM 6:45PM",
            "type": "LEC"
        },
        "1": {
            "cnum": "102",
            "cname": "Afro-American Music",
            "credits": 3,
            "pid": 1677,
            "lid": null,
            "honors": false,
            "location": "TBD",
            "gened": "AT,DU",
            "major": "MUSIC",
            "prereqs": "TBD",
            "time_of_day": "TU TH 8:00AM 9:15AM",
            "type": "LEC"
        },
        "2": {
            "cnum": "110",
            "cname": "Introduction to Sociology",
            "credits": 3,
            "pid": 170,
            "lid": null,
            "honors": false,
            "location": "TBD",
            "gened": "SB,DU",
            "major": "SOCIOL",
            "prereqs": "TBD",
            "time_of_day": "TU TH 8:30AM 9:45AM",
            "type": "LEC"
        },
        "3": {
            "cnum": "160",
            "cname": "My Body, My Health",
            "credits": 3,
            "pid": 232,
            "lid": null,
            "honors": false,
            "location": "TBD",
            "gened": "SI,DU",
            "major": "PUBHLTH",
            "prereqs": "TBD",
            "time_of_day": "TU TH 4:00PM 5:15PM",
            "type": "LEC"
        },
        "4": {
            "cnum": "187",
            "cname": "Gender, Sexuality and Culture",
            "credits": 3,
            "pid": 1457,
            "lid": null,
            "honors": false,
            "location": "TBD",
            "gened": "I,DU",
            "major": "WGSS",
            "prereqs": "TBD",
            "time_of_day": "TU TH 1:00PM 2:15PM",
            "type": "LEC"
        }
    },
    "1": {
        "0": {
            "cnum": "121",
            "cname": "Intro Problem Solving W/Comp",
            "credits": 4,
            "pid": 4,
            "lid": 100,
            "honors": false,
            "location": "TBD",
            "gened": "R2",
            "major": "COMPSCI",
            "prereqs": "TBD",
            "time_of_day": "TU TH 5:30PM 6:45PM",
            "type": "LEC"
        },
        "1": {
            "cnum": "102",
            "cname": "Roman Civilization",
            "credits": 3,
            "pid": 811,
            "lid": null,
            "honors": false,
            "location": "TBD",
            "gened": "HS",
            "major": "CLASSICS",
            "prereqs": "TBD",
            "time_of_day": "M W F 10:10AM 11:00AM",
            "type": "LEC"
        },
        "2": {
            "cnum": "140",
            "cname": "European History 1500-1815",
            "credits": 3,
            "pid": 528,
            "lid": null,
            "honors": false,
            "location": "TBD",
            "gened": "HS",
            "major": "HISTORY",
            "prereqs": "TBD",
            "time_of_day": "M W F 9:05AM 9:55AM",
            "type": "LEC"
        },
        "3": {
            "cnum": "101H",
            "cname": "Hnrs:Westrn Thought Since 1600",
            "credits": 3,
            "pid": 402,
            "lid": null,
            "honors": true,
            "location": "TBD",
            "gened": "HS",
            "major": "HISTORY",
            "prereqs": "TBD",
            "time_of_day": "TU TH 8:30AM 9:45AM",
            "type": "LEC"
        },
        "4": {
            "cnum": "181",
            "cname": "Hist Western Sci&Technology II",
            "credits": 4,
            "pid": 1568,
            "lid": 171,
            "honors": false,
            "location": "TBD",
            "gened": "HS",
            "major": "HISTORY",
            "prereqs": "TBD",
            "time_of_day": "M W 10:10AM 11:00AM",
            "type": "LEC"
        }
    },
    "2": {
        "0": {
            "cnum": "121",
            "cname": "Intro Problem Solving W/Comp",
            "credits": 4,
            "pid": 4,
            "lid": 100,
            "honors": false,
            "location": "TBD",
            "gened": "R2",
            "major": "COMPSCI",
            "prereqs": "TBD",
            "time_of_day": "TU TH 5:30PM 6:45PM",
            "type": "LEC"
        },
        "1": {
            "cnum": "170",
            "cname": "Grassroot Exp Amer Lfe & Cul I",
            "credits": 3,
            "pid": 1558,
            "lid": null,
            "honors": false,
            "location": "TBD",
            "gened": "HS,DU",
            "major": "AFROAM",
            "prereqs": "TBD",
            "time_of_day": "TU TH 10:00AM 11:15AM",
            "type": "LEC"
        },
        "2": {
            "cnum": "111",
            "cname": "World History since 1500",
            "credits": 4,
            "pid": 1282,
            "lid": 164,
            "honors": false,
            "location": "TBD",
            "gened": "HS,DG",
            "major": "HISTORY",
            "prereqs": "TBD",
            "time_of_day": "M W 10:10AM 11:00AM",
            "type": "LEC"
        },
        "3": {
            "cnum": "154",
            "cname": "Social Change in the 1960s",
            "credits": 3,
            "pid": 815,
            "lid": null,
            "honors": false,
            "location": "TBD",
            "gened": "HS,DU",
            "major": "HISTORY",
            "prereqs": "TBD",
            "time_of_day": "TU TH 10:00AM 11:15AM",
            "type": "LEC"
        }
    }
}`

export default js;